# Generated by Django 4.2.9 on 2026-09-07 13:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('overtimeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csv_content', models.TextField()),
                ('checksum', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField()),
                ('format_version', models.CharField(default='approval-review-v1', max_length=40)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('confirmed', 'Import confirmed'), ('failed', 'Import failed')], default='generated', max_length=20)),
                ('sap_reference', models.CharField(blank=True, max_length=100)),
                ('result_note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='requires_employee_assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='overtime_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_logs', to='overtimeapp.overtimerequest'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeassignment',
            name='overtime_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='overtimeapp.overtimerequest'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='request_id',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, help_text='Total employee-hours authorized in advance', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))]),
        ),
        migrations.AlterField(
            model_name='sapexport',
            name='overtime_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sap_export', to='overtimeapp.overtimerequest'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='ot_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(check=models.Q(('total_hours__gte', Decimal('0.5'))), name='ot_positive_hours'),
        ),
        migrations.AddConstraint(
            model_name='overtimerequest',
            constraint=models.CheckConstraint(check=models.Q(('hourly_rate__isnull', True), ('hourly_rate__gte', 0), _connector='OR'), name='ot_nonnegative_rate'),
        ),
        migrations.AddField(
            model_name='exportbatch',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='overtime_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='overtimeapp.overtimerequest'),
        ),
        migrations.AddField(
            model_name='sapexport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='overtimeapp.exportbatch'),
        ),
    ]
